version: '3.8'

services:
  zookeeper:
    image: debezium/zookeeper:${ZOOKEEPER_IMAGE_TAG}
    container_name: zookeeper
    restart: ${RESTART_POLICY}
    environment:
      - TZ
    ports:
    - 2181:2181

  kafka:
    image: debezium/kafka:${KAFKA_IMAGE_TAG}
    container_name: kafka
    restart: ${RESTART_POLICY}
    depends_on:
    - zookeeper
    environment:
      - TZ
      - ADVERTISED_LISTENERS
      - LISTENERS
      - ZOOKEEPER_CONNECT
    ports:
      - 9092:9092

  connect:
    image: debezium-connector-hana-min:${DEBEZIUM_IMAGE_TAG}
    container_name: connect
    restart: ${RESTART_POLICY}
    depends_on:
    - kafka
    environment:
      - TZ
      - BOOTSTRAP_SERVERS
      - CONNECT_CONFIG_PROVIDERS
      - CONNECT_CONFIG_PROVIDERS_FILE_CLASS
      - GROUP_ID
      - CONFIG_STORAGE_TOPIC
      - OFFSET_STORAGE_TOPIC
      - STATUS_STORAGE_TOPIC
    volumes:
      - ./hana-config:/kafka/custom-config
    ports:
      - 8083:8083

  kafdrop:
    image: obsidiandynamics/kafdrop:${KAFDROP_IMAGE_TAG}
    container_name: kafkawebui
    restart: ${RESTART_POLICY}
    depends_on:
      - kafka
    environment:
      - TZ
      - KAFKA_BROKERCONNECT
      - JVM_OPTS
    ports:
      - 9000:9000